"""Created Contribution and Transfer tables

Revision ID: e73b0b369a6f
Revises: 6bd9444a2665
Create Date: 2018-07-10 10:11:48.166224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73b0b369a6f'
down_revision = '6bd9444a2665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_timestamp'), 'transfer', ['timestamp'], unique=False)
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_timestamp'), 'contribution', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('account', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account')
    op.drop_index(op.f('ix_contribution_timestamp'), table_name='contribution')
    op.drop_table('contribution')
    op.drop_index(op.f('ix_transfer_timestamp'), table_name='transfer')
    op.drop_table('transfer')
    # ### end Alembic commands ###
